[pytest]


# Cpnfiguracion para ejecutar todos los archivos pytest que comiencen con test_
python_files = test_*.py
python_functions = test_*

# Generer reporte html
 # Se agrega -s para mostrar los print al momento de la ejecucion
addopts = -v -s --html=reports/reporte.html --self-contained-html
