[pytest]


    # Cpnfiguracion para ejecutar todos los archivos pytest que comiencen con test_
    pytest_files = test_*.py
    pytest_functions = test_*

    # Generer reporte html
    addopts = -v --html = reports/reporte.html --self-contained-html
